name: intercom_flutter_web
description: Web platform implementation of intercom_flutter
version: 0.0.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intercom_flutter_platform_interface:
    git:
      url: git@github.com:stanojevicboban/intercom_flutter_platform_interface.git
  uuid: ^2.2.2 # to get the random uuid for registerUnidentifiedUser in web

#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  mockito: ^5.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: ">=1.22.0"
